// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication.Models;

namespace Items.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210613174234_add-image-data")]
    partial class addimagedata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebApplication.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "good camera nokia phone",
                            MobileNumber = "9919291",
                            Title = "Mobile Phone "
                        },
                        new
                        {
                            Id = 2,
                            Description = "new audi car ",
                            MobileNumber = "121212",
                            Title = "Car "
                        },
                        new
                        {
                            Id = 3,
                            Description = "new xbox ",
                            MobileNumber = "121212",
                            Title = "Game Console"
                        },
                        new
                        {
                            Id = 4,
                            Description = "19th century table ",
                            MobileNumber = "121212",
                            Title = "Antique"
                        },
                        new
                        {
                            Id = 5,
                            Description = "4 floor house in village ",
                            MobileNumber = "121212",
                            Title = "New House"
                        },
                        new
                        {
                            Id = 6,
                            Description = "new mercedes-benz car ",
                            MobileNumber = "121212",
                            Title = "Car Selling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
