// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace Items.Migrations
{
    [DbContext(typeof(ItemFeedContext))]
    [Migration("20210611115929_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("WebApplication.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "good camera nokia phone",
                            MobileNumber = "9919291",
                            Title = "Mobile Phone "
                        },
                        new
                        {
                            Id = 2,
                            Description = "new audi car ",
                            MobileNumber = "121212",
                            Title = "Car "
                        },
                        new
                        {
                            Id = 3,
                            Description = "new xbox ",
                            MobileNumber = "121212",
                            Title = "Game Console"
                        },
                        new
                        {
                            Id = 4,
                            Description = "19th century table ",
                            MobileNumber = "121212",
                            Title = "Antique"
                        },
                        new
                        {
                            Id = 5,
                            Description = "4 floor house in village ",
                            MobileNumber = "121212",
                            Title = "New House"
                        },
                        new
                        {
                            Id = 6,
                            Description = "new mercedes-benz car ",
                            MobileNumber = "121212",
                            Title = "Car Selling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
